# Generated by Django 6.0 on 2025-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12, verbose_name='Логин')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
    ]
